spring:
  datasource:
    #? ?? sql db url???!!!! ????? ?? ?????? ?? sql url??????!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skhuringdb?useSSL=false
    username: root
    password: 258025
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

